# Generated by Django 5.1.4 on 2024-12-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_file_content_alter_myimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.URLField(),
        ),
    ]
