# Generated by Django 5.1.4 on 2024-12-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.URLField(),
        ),
    ]
