# Generated by Django 5.2.4 on 2025-07-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_remove_certification_link_categories_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Achievements",
        ),
    ]
