# Generated by Django 5.2.4 on 2025-07-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_delete_achievements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="Proficiency",
        ),
    ]
