# Generated by Django 5.1.4 on 2024-12-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0003_see_my_work_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='Work_Image',
            field=models.URLField(),
        ),
    ]
